## Import Library

In [1]:
import cv2
import numpy as np

## Read Image

In [2]:
citra = cv2.imread('logo.png')

## Show Image

In [3]:
cv2.imshow("citra asli", citra)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Split RGB Image

In [4]:
b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]

In [5]:
panjang = len(citra)
lebar = len(citra[0])

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j]

citra_gray = citra_gray.astype(np.uint8)

In [12]:
cv2.imshow("ABU", citra_gray)
cv2.waitKey() 
cv2.destroyAllWindows()


In [8]:
print(citra_gray)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
panjang = len(citra)
lebar = len(citra[0])

ambang = 210

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
          citra_biner[i,j] = 0
        else:
          citra_biner[i,j] = 1

In [13]:
cv2.imshow("biner", citra_biner)
cv2.waitKey() 
cv2.destroyAllWindows()

## Print pixel on specific index

In [14]:
print(citra_gray[50,50])

166


In [15]:
print(citra_biner[50,50])

1.0
